config/routes.rb
Rails.application.routes.draw do
  root                     'sessions#new'

  get '/login',        to: 'sessions#new',              as: 'login'
  post '/login',       to: 'sessions#create',           as: 'signin'
  delete '/logout',    to: 'sessions#destroy',          as: 'logout'

  resources :users
  get '/search',       to: 'users#search',              as: 'search'
  post '/search',      to: 'users#find',                as: 'find'
  get '/basic_info',   to: 'users#basic_info',          as: 'basic_info'
  patch '/basic_info', to: 'users#update_basic_info',   as: 'recalculate'

  resources :notes
  resources :measurements
  resources :fat_measurements
  
  post '/change_method', to: 'fat_measurements#change_method', as: 'change_method'
  
  resources :exercises
  resources :exercise_assignments, only: [:index, :create, :update, :destroy]
  
  post '/move_up',    to: 'exercise_assignments#move_up',   as: 'move_up'
  post '/move_down',  to: 'exercise_assignments#move_down', as: 'move_down'
  
  resources :exchanges, only: [:index, :create, :update, :destroy]
  resources :sub_exchanges, only: [:create, :update, :destroy]
  resources :foods, only: [:new, :create, :edit, :update, :destroy]
  resources :meals, only: [:index, :create, :update, :destroy]
  resources :food_assignments, only: [:create, :update, :destroy]
  
  post '/move_food_up',    to: 'food_assignments#move_food_up',   as: 'move_food_up'
  post '/move_food_down',  to: 'food_assignments#move_food_down', as: 'move_food_down'

  resources :supplement_brands, only: [:create, :update, :destroy]
  resources :supplement_products, only: [:create, :update, :destroy]
  resources :supplement_assignments, only: [:index, :create, :update, :destroy]
  
  get  '/import_all',                 to: 'users#import_all',           as: 'import_all'
  post '/import_users',               to: 'users#import',               as: 'import_users'
  post '/import_exchanges',           to: 'exchanges#import',           as: 'import_exchanges'
  post '/import_sub_exchanges',       to: 'sub_exchanges#import',       as: 'import_sub_exchanges'
  post '/import_foods',               to: 'foods#import',               as: 'import_foods'
  post '/import_supplement_brands',   to: 'supplement_brands#import',   as: 'import_supplement_brands'
  post '/import_supplement_products', to: 'supplement_products#import', as: 'import_supplement_products'
  post '/import_exercises',           to: 'exercises#import',           as: 'import_exercises'

  resources :videos, only: [:index, :create, :update, :destroy]
  
  post '/move_video_up',    to: 'videos#move_up',   as: 'move_video_up'
  post '/move_video_down',  to: 'videos#move_down', as: 'move_video_down'
  

end

app/models/supplement_assignment.rb
class SupplementAssignment < ActiveRecord::Base
	validates :number_of_servings, presence: true
	validates :user_id, presence: true
	validates :supplement_product_id, presence: true
	belongs_to :user
	belongs_to :supplement_product
	
	def servings_text
		if self.number_of_servings == 1
			"1 #{self.supplement_product.serving_type} of "
		else
			"#{"%g" % ("%.2f" % self.number_of_servings)} #{self.supplement_product.serving_type.pluralize} of "
		end
	end
	
	def serving_type_text
		if self.number_of_servings == 1
			"#{self.supplement_product.serving_type} of "
		else
			"#{self.supplement_product.serving_type.pluralize} of "
		end
	end
	
	def time_options
		[
			["Upon Waking, First Thing"],
			["Before Breakfast"],
			["Meal #1 (Breakfast)"],
			["Meal #2 (AM Snack)"],
			["Before Lunch"],
			["Meal #3 (Lunch)"],
			["Meal #4 (PM Snack)"],
			["Before Dinner"],
			["Meal #5 (Dinner)"],
			["Meal #6 (HS Snack if prescribed)"],
			["Before Workout"],
			["After Workout (15min After)"],
			["Bedtime"]
		]
	end
end

app/controllers/supplement_assignments_controller.rb
class SupplementAssignmentsController < ApplicationController
	before_action :set_supplement_assignment, only: [:update, :destroy]

  def index
    if authorized_to_see
      @supplement_assignments = focussed_user.supplement_assignments.order(:time_of_day)
      @new_sa = focussed_user.supplement_assignments.new
      @my_supplement_products = SupplementProduct.joins(:user).where("users.license = ? OR users.id = ?", 
		    "owner", @new_sa.user.trainer_id ).distinct
		    
      if current_license != "owner" 
        if current_license != "client"
          
          if current_license == "employee"
            @my_supplement_brands   = current_user.employer.supplement_brands
            @my_supplement_products = current_user.employer.supplement_products
          else
            @my_supplement_brands   = current_user.supplement_brands
            @my_supplement_products = current_user.supplement_products
          end
          
          owner_supplement_brands   = SupplementBrand.joins(   :user).where(users: { license: "owner" })
          owner_supplement_products = SupplementProduct.joins( :user).where(users: { license: "owner" })
          
      	  @supplement_brands    = (@my_supplement_brands    || []) + (owner_supplement_brands   || [])
      	  @supplement_products  = (@my_supplement_products  || []) + (owner_supplement_products || [])
        end
      else
        @supplement_brands      = SupplementBrand.all
        @supplement_products    = SupplementProduct.all
        @my_supplement_brands   = @supplement_brands
        @my_supplement_products = @supplement_products
      end

    else
      flash[:danger] = "You are not authorized to view this client's supplements"
      redirect_to root_path
    end
  end
	
	def create
		if authorized_to_edit(focussed_user)
      
      params[:supplement_assignment][:number_of_servings] = 1 unless 
        params[:supplement_assignment][:number_of_servings]
      @supplement_assignment = focussed_user.supplement_assignments.build(supplement_assignment_params)

      if !@supplement_assignment.save
      	flash[:danger] = "Supplement assignment didn't save!"
      end
      redirect_to supplement_assignments_path
      
    else
      flash[:danger] = "You are not authorized to add supplements for this client"
      redirect_to root_path
		end
	end
	
	def update
		if authorized_to_edit(@supplement_assignment.user)
		  	  
      if @supplement_assignment.update_attributes(supplement_assignment_params)
         flash[:success] = "Supplement assignment updated"
      else
        flash[:danger] = "Supplement assignment didn't save!"
      end
      redirect_to supplement_assignments_path
      
    else
      flash[:danger] = "You are not authorized to edit this supplement assignment!"
      redirect_to root_path
		end
		
	end
	
	def destroy
		if authorized_to_edit(@supplement_assignment.user)
      @supplement_assignment.destroy
      flash[:success] = "Supplement assignment deleted"
      redirect_to supplement_assignments_path
    else
      flash[:danger] = "You are not authorized to delete this Supplement assignment!"
      redirect_to root_path
		end
	end
	
	private

		# Use callbacks to share common setup or constraints between actions.
    def set_supplement_assignment
      @supplement_assignment = SupplementAssignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplement_assignment_params
      params.require(:supplement_assignment).permit(
				:user_id, :supplement_product_id, :number_of_servings, :time_of_day
      )
    end
    
    def authorized_to_edit(user)
			current_license == "owner" ||
			
			(current_license != "client" && 
       current_user.clients.include?(user)
      )
    end
    
    def authorized_to_see
			current_license == "owner" ||
			 
			current_user == focussed_user ||
			
			(current_license != "client" && 
       current_user.clients.include?(focussed_user)
      )
    end
	
end

app/helpers/supplement_assignments_helper.rb
module SupplementAssignmentsHelper
end

app/views/supplement_assignments/_client_supplement_form.html.erb
<td class="text-center"><%= @sa.time_of_day %></td>
<td colspan="2" class="col-md-2 text-center"><%= @sa.servings_text %></td>
<td colspan="10"><%= @sa.supplement_product.drop_down_text %></td>

app/views/supplement_assignments/_non_client_supplement_form.html.erb
<%= form_for :supplement_assignment, url: supplement_assignment_path(@sa), method: :patch do |f| %>	
	<td class="text-center"><%= f.select :time_of_day, options_for_select(@sa.time_options, @sa.time_of_day), include_blank: true %></td>
	<td>
		<%= f.text_field :number_of_servings, value: "%g" % ("%.2f" % @sa.number_of_servings), 
				class: "text-right" %>
	</td>
	<td class="col-md-1"><%= @sa.serving_type_text %></td>
	<td>
		<%= f.collection_select :supplement_product_id, @my_supplement_products, :id, :drop_down_text, 
				{selected: @sa.supplement_product.id}, include_blank: true %>
	</td>
	<td class="hide-on-print"><a><%= f.submit 'Update', class: "submit-link" %></a></td>
	<td class="hide-on-print">
		<%= link_to 'Remove', @sa, method: :delete, data: {confirm: 'Are you sure?'} %>
	</td>
<% end %>

app/views/supplement_assignments/_supplement_brands.html.erb
<% if !@supplement_brands.blank? %>
	<div class="meal-table">
		<table class="table">
			<tr>
				<th>Brand</th>
				<th>Product</th>
				<th>Package Type<br/>(e.g. box, bottle, etc.)</th>
				<th>Serving Type<br/>(e.g. pill, bar, etc.)</th>
				<th>Servings Per Package</th>
				<% if current_license == "owner" %>
					<th colspan="3" class="text-right">(Creator)</th>
				<% end %>
			</tr>
			<% @supplement_brands.each do |b| %>
				<tr>
					<% if @my_supplement_brands && @my_supplement_brands.include?(b) %>
							
						<%= form_for(:supplement_brand, url: supplement_brand_path(b), method: :patch) do |f| %>
							<td colspan="5"><%= f.text_field :name, value: b.name, class: "table-text" %></td>
							<td><a><%= f.submit 'Update', class: "submit-link" %></a></td>
							<td>
								<%= link_to 'Delete', supplement_brand_path(b), method: :delete, 
										data: {confirm: 'Are you sure? This will also delete all associated supplement products and Meal Plan entries.'} %>
							</td>
							<% if current_license == "owner" %>
								<td class="text-right">
									<%= "(#{b.user.name})" %>
								</td>
							<% end %>
						<% end %>
										
					<% else %>
						<td colspan="7"><%= b.name %></td>
					<% end %>
				</tr>								
				<% @b = b %>
				<%= render 'supplement_products' %>
			<% end %>
		</table>
	</div>
<% end %>

<table class="table">
	<%= form_for(:supplement_brand, url: supplement_brands_path, method: :post) do |f| %>
	<tr>
			<td><%= f.text_field :name, class: "table-text" %></td>
			<td><%= f.submit 'Add New Supplement Brand', class: "btn-sm btn-primary" %></td>
		</tr>
	<% end %>
</table>

app/views/supplement_assignments/_supplement_products.html.erb
<% if !(@b.supplement_products & @supplement_products).nil? %>
	<% (@b.supplement_products & @supplement_products).each do |s| %>
		<tr>
			<td></td>
			<% if @my_supplement_products && @my_supplement_products.include?(s) %>
					
				<%= form_for(:supplement_product, url: supplement_product_path(s), method: :patch) do |f| %>
					<td><%= f.text_field :name, value: s.name, class: "table-text" %></td>
					<td><%= f.text_field :retail_package_type, value: s.retail_package_type, class: "table-text" %></td>
					<td><%= f.text_field :serving_type, value: s.serving_type, class: "table-text" %></td>
					<td><%= f.text_field :servings_per_bottle, value: "%g" % ("%.2f" % s.servings_per_bottle), class: "table-text" %></td>
					<td><a><%= f.submit 'Update', class: "submit-link" %></a></td>
					<td>
						<%= link_to 'Delete', supplement_product_path(s), method: :delete, 
								data: {confirm: 'Are you sure? This will also delete all associated Meal Plan entries.'} %>
					</td>
					<% if current_license == "owner" %>
						<td class="text-right">
							<%= "(#{s.user.name})" %>
						</td>
					<% end %>
				<% end %>
								
			<% else %>
				<td><%= s.name %></td>
				<td><%= s.retail_package_type %></td>
				<td><%= s.serving_type %></td>
				<td><%= "%g" % ("%.2f" % s.servings_per_bottle) %></td>
				<td></td>
				<td></td>
			<% end %>
		</tr>
	<% end %>
<% end %>

<%= form_for(:supplement_product, url: supplement_products_path, method: :post) do |f| %>
	<tr>
		<%= f.hidden_field :supplement_brand_id, value: @b.id %>
		<td></td>
		<td><%= f.text_field :name, class: "table-text" %></td>
		<td><%= f.text_field :retail_package_type, class: "table-text" %></td>
		<td><%= f.text_field :serving_type, class: "table-text" %></td>
		<td><%= f.text_field :servings_per_bottle, class: "table-text" %></td>
		<td colspan="2"><%= f.submit 'Add New Product', class: "btn-sm btn-primary" %></td>
	</tr>
<% end %>

app/views/supplement_assignments/_supplement_summary.html.erb
<% unless focussed_user.supplements_summary.blank? %>
	<div class="text-center big">Supplements Needed</div>
	<table class="table">
		<tr>
			<th>Supplement</th>
			<th>Per Week</th>
			<th>Per Month</th>
		</tr>
		<% focussed_user.supplements_summary.each do |ss| %>
			<tr>
				<td><%= ss[:name] %></td>
				<td><%= ss[:per_week] %></td>
				<td><%= ss[:per_month] %></td>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/supplement_assignments/index.html.erb
<table class="table">
	<tr>
		<th class="text-center">Time of Day</th>
		<th colspan=2 class="col-md-2 text-center">Servings</th>
		<th colspan="3" class="col-md-6">Product</th>
	</tr>

	<!-- list of assigned supplements -->
	<% unless @supplement_assignments.nil? %>
			<% @supplement_assignments.each do |sa| %>
				<tr>
					<% @sa = sa %>
					<% if current_license == "client" %>
						<%= render 'client_supplement_form' %>
					<% else %>
						<div id="supplement_form<%= sa.id %>">
							<%= render 'non_client_supplement_form' %>
						</div>
					<% end %>
				</tr>
			<% end %>
	<% end %>

	<!-- prescribe new supplements -->
	<% unless current_license == "client" %>
		<%= form_for :supplement_assignment, url: supplement_assignments_path, method: :post do |f| %>
			<tr class="hide-on-print">
				<td class="text-center">
					<%= f.select :time_of_day, options_for_select(@new_sa.time_options), include_blank: true %>
				</td>
				<td class="text-right"><%= f.text_field :number_of_servings %></td>
				<td></td>
				<td>
					<%= f.collection_select :supplement_product_id, @my_supplement_products, :id, :drop_down_text,
							include_blank: true%>
					<%= f.hidden_field(:user_id, value: focussed_user.id) %>
				</td>
				<td colspan="2"><%= f.submit "Add New Supplement", class: "btn-sm btn-primary" %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<!-- monthly supplement amounts -->
<div id="supplement_summary">
	<%= render "supplement_summary" %>
</div>
<br>
<br>

<!-- add new and list supplements -->
<% unless current_license == "client" %>
	<h2>Available Supplements</h2>
	<%= render 'supplement_brands' %>
<% end %>