config/routes.rb
Rails.application.routes.draw do
  root                     'sessions#new'

  get '/login',        to: 'sessions#new',              as: 'login'
  post '/login',       to: 'sessions#create',           as: 'signin'
  delete '/logout',    to: 'sessions#destroy',          as: 'logout'

  resources :users
  get '/search',       to: 'users#search',              as: 'search'
  post '/search',      to: 'users#find',                as: 'find'
  get '/basic_info',   to: 'users#basic_info',          as: 'basic_info'
  patch '/basic_info', to: 'users#update_basic_info',   as: 'recalculate'

  resources :notes
  resources :measurements
  resources :fat_measurements
  
  post '/change_method', to: 'fat_measurements#change_method', as: 'change_method'
  
  resources :exercises
  resources :exercise_assignments, only: [:index, :create, :update, :destroy]
  
  post '/move_up',    to: 'exercise_assignments#move_up',   as: 'move_up'
  post '/move_down',  to: 'exercise_assignments#move_down', as: 'move_down'
  
  resources :exchanges, only: [:index, :create, :update, :destroy]
  resources :sub_exchanges, only: [:create, :update, :destroy]
  resources :foods, only: [:new, :create, :edit, :update, :destroy]
  resources :meals, only: [:index, :create, :update, :destroy]
  resources :food_assignments, only: [:create, :update, :destroy]
  
  post '/move_food_up',    to: 'food_assignments#move_food_up',   as: 'move_food_up'
  post '/move_food_down',  to: 'food_assignments#move_food_down', as: 'move_food_down'

  resources :supplement_brands, only: [:create, :update, :destroy]
  resources :supplement_products, only: [:create, :update, :destroy]
  resources :supplement_assignments, only: [:index, :create, :update, :destroy]
  
  get  '/import_all',                 to: 'users#import_all',           as: 'import_all'
  post '/import_users',               to: 'users#import',               as: 'import_users'
  post '/import_exchanges',           to: 'exchanges#import',           as: 'import_exchanges'
  post '/import_sub_exchanges',       to: 'sub_exchanges#import',       as: 'import_sub_exchanges'
  post '/import_foods',               to: 'foods#import',               as: 'import_foods'
  post '/import_supplement_brands',   to: 'supplement_brands#import',   as: 'import_supplement_brands'
  post '/import_supplement_products', to: 'supplement_products#import', as: 'import_supplement_products'
  post '/import_exercises',           to: 'exercises#import',           as: 'import_exercises'

  resources :videos, only: [:index, :create, :update, :destroy]
  
  post '/move_video_up',    to: 'videos#move_up',   as: 'move_video_up'
  post '/move_video_down',  to: 'videos#move_down', as: 'move_video_down'
  

end

app/models/video.rb
class Video < ActiveRecord::Base
	before_save :capitalize
	before_create :capitalize
	validates :title, presence: true
	validates :url, presence: true

	private
	
		def capitalize
			self.title = self.title.titleize if !self.title.blank?
		end
	
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :set_video, only: [:update, :destroy, :move_up, :move_down]
	before_action :check_license, only: [:create, :update, :destroy, :move_up, :move_down]
	
	def index
		@videos = Video.all.order(:position)
		count = 1
		@videos.each do |video|
			if video.position.blank?
				video.update(position: count)
			end
			count += 1
		end
	end
	
	def create
		@video = Video.new(video_params)
		if @video.save
			flash[:success] = 'Video saved'
    else
    	flash[:danger] = 'Video failed to save'
		end
    redirect_to videos_path
	end
	
	def update
		if @video.update(video_params)
			flash[:success] = 'Video saved'
    else
    	flash[:danger] = 'Video failed to save'
		end
    redirect_to videos_path
	end
	
	def destroy
		if @video.destroy
			flash[:success] = 'Video deleted'
    else
    	flash[:danger] = 'Video failed to delete'
		end
    redirect_to videos_path
	end
	
	def move_up
		above = Video.where("position = ?", @video.position - 1)
		above.update_all(position: @video.position) if above.size > 0
		@video.update(position: @video.position - 1)
		redirect_to videos_path
	end
	
	def move_down
		below = Video.where("position = ?", @video.position + 1)
		below.update_all(position: @video.position) if below.size > 0
		@video.update(position: @video.position + 1)
		redirect_to videos_path
	end

	private
		def video_params
			params.require(:video).permit(:title, :url, :description)
		end
		
		def set_video
			@video = Video.find(params[:id])
		end
		
		def check_license
			if current_license != "owner"
				flash[:danger] = "You are not authorized to change videos."
				redirect_to videos_path
			end
		end
	
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_owners_view.html.erb
<!-- Edit/see each video -->
<% @videos.each do |video| %>
	<div class="sub-table">
	<%= form_for(:video, url: video_path(video), method: :patch) do |f| %>
		<%= f.text_field :title, value: video.title, class: "text-center video-title" %>
		<%= f.text_field :url, value: video.url, class: "text-center"%>
		
		<div class="text-center">
			<%= content_tag(:iframe, nil, src: "#{video.url}", class: "video-player", allowfullscreen: true) %>
		</div>
		
		<div class="text-center">Description:<%= f.text_area :description, value: video.description %></div>

		<div class="text-center">
     	<% if video.position > 1 %>
      	<%= link_to move_video_up_path(id: video.id), method: :post do %>
       		<i class="glyphicon glyphicon-arrow-up"></i>
     		<% end %>
			<% end %>      	
			<% if video.position < @videos.length %>
      	<%= link_to move_video_down_path(id: video.id), method: :post do %>
       		<i class="glyphicon glyphicon-arrow-down"></i>
     		<% end %>
     	<% end %>
		</div>

		<div class="text-center"><%= f.submit 'Update', class: "btn btn-primary" %></div>
		<div class="text-center">
			<%= link_to 'Delete', video_path(video), method: :delete, data: {confirm: 
				'Are you sure that you want to delete this video?'} %>
		</div>

	<% end %>
	</div><br>
<% end %>

<!-- enter new videos -->
<h2>Enter New Video</h2>
<%= form_for(:video, url: videos_path, method: :post) do |f| %>
	<table class="table">
		<tr>
			<th class="col-md-3">Video Title</th>
			<th class="col-md-9">url</th>
		</tr>
		<tr>
			<td><%= f.text_field :title %></td>
			<td><%= f.text_field :url %></td>
		</tr>
	</table>
	<div class="text-center">Description:<%= f.text_area :description %></div>
	<div class="text-center">
		<%= f.submit 'Save New Video', class: "btn btn-primary" %>
	</div>
<% end %>

app/views/videos/_users_view.html.erb
<% @videos.each do |video| %>
	<div class="sub-table">
		<div class="text-center video-title"><%= video.title %></div>
		<div class="text-center">
			<%= content_tag(:iframe, nil, src: "#{video.url}", class: "video-player", allowfullscreen: true) %>
		</div>
		<div class="video-description"><%= video.description %></div>
	</div><br>
<% end %>

app/views/videos/index.html.erb
<h1>Instructional Videos</h1>
<% if current_license == "owner" %>
	<%= render "owners_view" %>
<% else %>
	<%= render "users_view" %>
<% end %>