config/routes.rb
Rails.application.routes.draw do
  root                     'sessions#new'

  get '/login',        to: 'sessions#new',              as: 'login'
  post '/login',       to: 'sessions#create',           as: 'signin'
  delete '/logout',    to: 'sessions#destroy',          as: 'logout'

  resources :users
  get '/search',       to: 'users#search',              as: 'search'
  post '/search',      to: 'users#find',                as: 'find'
  get '/basic_info',   to: 'users#basic_info',          as: 'basic_info'
  patch '/basic_info', to: 'users#update_basic_info',   as: 'recalculate'

  resources :notes
  resources :measurements
  resources :fat_measurements
  
  post '/change_method', to: 'fat_measurements#change_method', as: 'change_method'
  
  resources :exercises
  resources :exercise_assignments, only: [:index, :create, :update, :destroy]
  
  post '/move_up',    to: 'exercise_assignments#move_up',   as: 'move_up'
  post '/move_down',  to: 'exercise_assignments#move_down', as: 'move_down'
  
  resources :exchanges, only: [:index, :create, :update, :destroy]
  resources :sub_exchanges, only: [:create, :update, :destroy]
  resources :foods, only: [:new, :create, :edit, :update, :destroy]
  resources :meals, only: [:index, :create, :update, :destroy]
  resources :food_assignments, only: [:create, :update, :destroy]
  
  post '/move_food_up',    to: 'food_assignments#move_food_up',   as: 'move_food_up'
  post '/move_food_down',  to: 'food_assignments#move_food_down', as: 'move_food_down'

  resources :supplement_brands, only: [:create, :update, :destroy]
  resources :supplement_products, only: [:create, :update, :destroy]
  resources :supplement_assignments, only: [:index, :create, :update, :destroy]
  
  get  '/import_all',                 to: 'users#import_all',           as: 'import_all'
  post '/import_users',               to: 'users#import',               as: 'import_users'
  post '/import_exchanges',           to: 'exchanges#import',           as: 'import_exchanges'
  post '/import_sub_exchanges',       to: 'sub_exchanges#import',       as: 'import_sub_exchanges'
  post '/import_foods',               to: 'foods#import',               as: 'import_foods'
  post '/import_supplement_brands',   to: 'supplement_brands#import',   as: 'import_supplement_brands'
  post '/import_supplement_products', to: 'supplement_products#import', as: 'import_supplement_products'
  post '/import_exercises',           to: 'exercises#import',           as: 'import_exercises'

  resources :videos, only: [:index, :create, :update, :destroy]
  
  post '/move_video_up',    to: 'videos#move_up',   as: 'move_video_up'
  post '/move_video_down',  to: 'videos#move_down', as: 'move_video_down'
  

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  def index

    if current_license == "employee"
      @my_exercises = current_user.employer.exercises
    elsif current_license != "client"
      @my_exercises = current_user.exercises
    end
    
    if current_license == "client"
      @trainer_exercises = current_user.trainer.exercises
    end

    @owner_exercises = Exercise.joins(:user).
      where(users: { license: "owner" })

    if current_license != "owner"
      @exercises = (@my_exercises || []) + (@owner_exercises || []) +
        (@trainer_exercises || [])
    else
      @exercises = Exercise.all
    end
    
    @authorized_to_change = authorized_to_change(@exercise)
    @cardio , @resistance = [], []
    @exercises.each do |exercise|
      @cardio << exercise if exercise.category == 'Cardiovascular'
      @resistance << exercise if exercise.category == 'Resistance'
    end
  end

  def show
    if !authorized_to_see(@exercise)
      flash[:danger] = "You are not authorized to see that exercise"
      redirect_to root_path
    end
    @authorized_to_change = authorized_to_change(@exercise)
  end

  # GET /exercises/new
  def new
    if current_license == "client"
      flash[:danger] = "You are not authorized to create exercises"
      redirect_to root_path
    else
      @exercise = Exercise.new
    end
  end

  # GET /exercises/1/edit
  def edit
    if !authorized_to_change(@exercise)
      flash[:danger] = "You are not authorized to edit this exercise"
      redirect_to root_path
    end
  end

  def create
    if current_license == "client"
      flash[:danger] = "You are not authorized to create exercises"
      redirect_to root_path
    else
      if current_license == "employee"
        @exercise = current_user.employer.exercises.new(exercise_params)
      else      
        @exercise = current_user.exercises.new(exercise_params)
      end

      if @exercise.save
        flash[:success] = 'Exercise was successfully created.'
        redirect_to exercises_path
      else
        flash.now[:danger] = "Exercise failed to save!"
        render :new
      end
    end
  end

  def update
    if !authorized_to_change(@exercise)
      flash[:danger] = "You are not authorized to edit this exercise"
      redirect_to root_path
    else
    
      if @exercise.update(exercise_params)
        flash[:success] = 'Exercise was successfully updated.'
        redirect_to exercises_path
      else
        flash.now[:danger] = "Changes failed to save"
        render :edit
      end
    end
  end

  def destroy
    if !authorized_to_change(@exercise) || 
        current_license == "employee"
      flash[:danger] = "You are not authorized to delete this exercise"
      redirect_to root_path
    elsif @exercise.destroy
      flash[:success] = 'Exercise was deleted.'
      redirect_to exercises_path
    end
  end
  
  def import
		csv_file = File.read(params[:file].tempfile.to_path.to_s)
		Exercise.import(csv_file)
		redirect_to import_all_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(
        :name, :description, :Kcal_per_kg_per_hr, :category
      )
    end
    
    def authorized_to_change(exercise)
			current_license == "owner" ||
			
			(current_license != "client" && 
       current_user.exercises.include?(exercise)
      ) ||
      
			(current_license == "employee" &&
			 current_user.employer.exercises.include?(exercise)
			)
    end
    
    def authorized_to_see(exercise)
			current_license == "owner" ||
			 
			exercise.user.license == "owner" ||
			
			(current_license != "client" && 
       current_user.exercises.include?(exercise)
      ) ||
      
			(current_license == "employee" &&
			 current_user.employer.exercises.include?(exercise)
			) ||
			
			(current_license == "client" &&
			  current_user.trainer.exercises.include?(exercise)
			)
    end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(:exercise, url: exercises_path, 
			method: :post, html: {class: "form-horizontal"}) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="row form-group col-md-offset-3 padded-5">
		<%= f.label :name, class: "control-label col-md-1" %>
		<div class="col-md-8 col-md-offset-1">
			<%= f.text_field :name, class: 'form-control' %>
		</div>
	</div>
	
	<div class="row form-group col-md-offset-3 padded-5">
		<%= f.label :category, class: "control-label col-md-1" %>
		<div class="col-md-8 col-md-offset-1">
			<%= f.select :category, options_for_select(
          ["Cardiovascular", "Resistance"], @exercise.category),
          {include_blank: false}, class: "form-control" %>
		</div>
	</div>
	
	<div class="row form-group col-md-offset-3 padded-5">
		<%= f.label :description, class: "control-label col-md-1" %>
		<div class="col-md-8 col-md-offset-1">
			<%= f.text_area :description, cols: 3, rows: 3,
		    	class: 'form-control' %>
		</div>
	</div>
	
	<div class="row form-group col-md-offset-3 padded-5">
		<%= f.label "Kcal/Kg/hr", class: "control-label col-md-1" %>
		<div class="col-md-8 col-md-offset-1">
			<% default = sprintf("%0.2f", @exercise.Kcal_per_kg_per_hr) if 
				@exercise.Kcal_per_kg_per_hr %>
			<%= f.text_field :Kcal_per_kg_per_hr, value: default, class: 'form-control' %>
		</div>
	</div>

	<div class="row form-group col-md-offset-3 padded-5">
		<%= f.label "Kcal/hr", class: "control-label col-md-1" %>
		<div class="col-md-8 col-md-offset-1">
			<% if @exercise.kcal_per_hr %>
				<% default = sprintf("%0.2f", @exercise.kcal_per_hr) %>
			<% else %>
				<% default = nil %>
			<% end %>
			<%= f.text_field :kcal_per_hr, value: default, class: 'form-control' %>
		</div>
	</div>

  <div class="text-center">
		<%= f.submit @submit_text, class: 'btn btn-primary' %>
	</div>

<% end %>

app/views/exercises/_index_table.html.erb
<table class="table table-striped table-bordered">
  <!-- <thead> -->
    <tr>
      <% if current_license == "owner" %>
        <th class="text-center col-md-2">Creator</th>
      <% end %>
      <th class="text-center col-md-3">Name</th>
      <th class="text-center col-md-5">Descrption</th>
      <th class="text-center col-md-1">Kcal/Kg/hr</th>
      <th class="text-center col-md-1">Kcal/hr</th>
      <th colspan="2"></th>
    </tr>
  <!-- </thead> -->

  <!-- <tbody> -->
    <% @show.each do |exercise| %>
      <tr>
        <% if current_license == "owner" %>
          <td><%= exercise.user.name %></th>
        <% end %>
        <td><%= exercise.name %></td>
        <td><%= exercise.description %></td>
        <td><%= exercise.Kcal_per_kg_per_hr %></td>
        <td><%= exercise.kcal_per_hr %></td>
        <% if @authorized_to_change %>
          <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
          <% if current_license != "employee" %>
            <td><%= link_to 'Delete', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  <!-- </tbody> -->
</table>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<% @submit_text = "Update Exercise" %>
<%= render 'form' %>

<div  class="text-center">
	<%= link_to 'Back', exercises_path %>
</div>

app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exercises</h1>

<h2 class="text-left">Cardiovascular Exercises</h2>
<% @show = @cardio %>
<%= render 'index_table' %>

<br>
<br>

<h2 class="text-left">Resistance Exercises</h2>
<% @show = @resistance %>
<%= render 'index_table' %>

<div class="text-center">
  <%= link_to 'New Exercise', new_exercise_path, 
      class: 'btn btn-primary' %>
</div>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<% @submit_text = "Create Exercise" %>
<%= render 'form' %>

<div  class="text-center">
	<%= link_to 'Back', exercises_path %>
</div>

app/views/exercises/show.html.erb
<h1><%= @exercise.name %></h1>
<div class="text-center">Description: <%= @exercise.description %></div>
<div class="text-center">KCal/kg/hr: <%= @exercise.Kcal_per_kg_per_hr %></div>

<div class="text-center">
	<% if @authorized_to_change %>
		<%= link_to 'Edit', edit_exercise_path(@exercise), 
				class: 'btn btn-primary' %>
	<% end %>
	<br>
	<%= link_to 'Back', exercises_path %>
</div>